### ISSUE TITLE
Create homepage UI

### ISSUE THREAD

**Issue by Trypt-Up** [EECE3093C/team-project-the-b-team-frontend#15]

**Comment by nickyd3438** [comment]
Is there any updates on this  Scott? I know that there were some changes that you had made just not committed yet. I have resources on the back end that would let us get through this sprint.

**Comment by Trypt-Up** [comment]
> 

Homepage doesn't look pretty but it has most of the necessary info- still need to add functionality for user to login on homescreen along with accessing their profile. I will break this up into smaller issues, sorry for the late response.
